@host=http://localhost:5180

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Big",
    "lastName": "Boss",
    "email": "randomemail@gmail.com",
    "password": "password"
}
